services:
  nginx:
    build: etc/nginx/
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    links:
      - app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: python/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    env_file:
      .env
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
      - ./python:/home/webapp
      - ./logs/python:/var/log/python
    ports:
      - "8080:8080"
    init: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    user: mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3306 > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 30s

  memcached:
    image: memcached:1.6
    ports:
      - "11211:11211"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g

  # newrelic-infra:
  #   build: logs/newrelic/
  #   cap_add:
  #     - SYS_PTRACE
  #   network_mode: host
  #   privileged: true
  #   pid: host
  #   env_file:
  #     .env
  #   volumes:
  #     - "/:/host:ro"
  #     - "/var/run/docker.sock:/var/run/docker.sock"

  # netdata:
  #   image: netdata/netdata:stable
  #   container_name: netdata
  #   pid: host
  #   cap_add:
  #     - SYS_PTRACE
  #     - SYS_ADMIN
  #   security_opt:
  #     - apparmor:unconfined
  #   volumes:
  #     - /etc/passwd:/host/etc/passwd:ro
  #     - /etc/group:/host/etc/group:ro
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /etc/os-release:/host/etc/os-release:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./logs/netdata:/etc/netdata
  #   ports:
  #     - 19999:19999
  #   # mysqlコンテナはhealth checkが通っていてもアクセスできるようになるまで時間かかるのでその対策
  #   depends_on:
  #     nginx:
  #       condition: service_started
  #     app:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #     memcached:
  #       condition: service_started

volumes:
  mysql:
